"""
Run this once in Supabase SQL editor (create child table for multi-entry details):

create table if not exists public.task_details (
  id bigint generated by default as identity primary key,
  task_id bigint not null,
  title text,
  url text,
  keywords text,
  description text,
  created_at timestamptz default now(),
  constraint fk_task
    foreign key (task_id)
    references public.tasks(id)
    on delete cascade
);

create index if not exists idx_task_details_task_id on public.task_details(task_id);
"""

import streamlit as st
from supabase import create_client
from datetime import date
import pandas as pd
import plotly.express as px

# ---------------- PAGE & CLIENT ----------------
st.set_page_config(page_title="Advanced CRM - Task Manager", page_icon="📋", layout="wide")

SUPABASE_URL = "https://fijvjhbhxdbinqdiiytq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpanZqaGJoeGRiaW5xZGlpeXRxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzkxNTk5OSwiZXhwIjoyMDczNDkxOTk5fQ.8tZln8rHlB_OpDG4q_w3TeRTdJyPKQJr_OF-q7QlGz8"
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# Compatibility helper for Streamlit rerun across versions
try:
    _rerun = st.rerun          # New API
except AttributeError:
    _rerun = st.experimental_rerun  # Old API

# ---------------- DEFAULT TASK TYPES ----------------
DEFAULT_TASK_TYPES = [
    "Forum Submission", "SBM", "Social Bookmarking", "Web 2.0/Profile Creation",
    "Podcast", "Classified Ads", "Forum Posting", "Q&A / Quora Submission",
    "Blog Submission", "Mini blog/article submission", "Tier-2 Backlinks",
    "Image Submission", "Blog SEO", "Document Sharing/PDF Sharing",
    "Infographic Submission / Business listings", "Guest Posting",
    "Competitor Backlinks", "Indexed Blogs (Wordpress, Blogger, Weebly)",
    "Social Signals", "On-page Blog", "Create Lost Backlinks"
]

# ---------------- UTIL ----------------
def _to_datestr(d):
    return d if isinstance(d, str) else d.strftime("%Y-%m-%d")

def _link(url: str) -> str:
    if not url:
        return ""
    return f"[{url}]({url})"

# ---------------- AUTH HELPERS (demo only) ----------------
def add_user(username, password, role):
    supabase.table("users").insert({"username": username, "password": password, "role": role}).execute()

def update_user(old_username, new_username, new_role):
    supabase.table("users").update({"username": new_username, "role": new_role}).eq("username", old_username).execute()

def delete_users(usernames):
    for username in usernames:
        supabase.table("users").delete().eq("username", username).execute()

def login_user(username, password):
    response = supabase.table("users").select("*").eq("username", username).eq("password", password).execute()
    return response.data[0] if response.data else None

def get_all_users():
    return supabase.table("users").select("*").execute().data

# ---------------- TASK TYPE HELPERS ----------------
def get_all_task_types():
    response = supabase.table("task_types").select("*").execute()
    if not response.data:
        for t in DEFAULT_TASK_TYPES:
            supabase.table("task_types").insert({"task_name": t}).execute()
        response = supabase.table("task_types").select("*").execute()
    return [t['task_name'] for t in response.data]

def add_task_type(task_name):
    supabase.table("task_types").insert({"task_name": task_name}).execute()

# ---------------- TASK HELPERS ----------------
def assign_task_with_details(users, tasks_with_qty, date_val, deadline, remarks="", details_list=None):
    """
    Creates tasks and attaches multiple detail rows to each created task.
    Compatible with older supabase-py (no .insert(...).select()).
    details_list: list of dicts like {"title":..., "url":..., "keywords":..., "description":...}
    """
    date_str = _to_datestr(date_val)
    deadline_str = _to_datestr(deadline)
    details_list = details_list or []

    for user in users:
        for task_name, qty in tasks_with_qty.items():
            payload = {
                "assigned_to": user,
                "task": task_name,
                "status": "Pending",
                "date": date_str,
                "deadline": deadline_str,
                "quantity": int(qty),
                "remarks": remarks
            }

            # 1) Insert (no .select() chaining for older libs)
            ins = supabase.table("tasks").insert(payload).execute()

            # 2) Resolve task_id from insert response or fallback lookup
            task_id = None
            if getattr(ins, "data", None):
                try:
                    task_id = ins.data[0]["id"]
                except (IndexError, KeyError, TypeError):
                    task_id = None

            if task_id is None:
                # Fallback read (best-effort, using identifying fields)
                lookup = (
                    supabase.table("tasks")
                    .select("id")
                    .eq("assigned_to", user)
                    .eq("task", task_name)
                    .eq("date", date_str)
                    .eq("deadline", deadline_str)
                    .order("id", desc=True)
                    .limit(1)
                    .execute()
                )
                if getattr(lookup, "data", None):
                    task_id = lookup.data[0]["id"]

            if not task_id:
                # Couldn’t resolve inserted row; skip attaching details for this one
                continue

            # 3) Attach details (if any)
            if details_list:
                child_rows = []
                for d in details_list:
                    if not any([d.get("title"), d.get("url"), d.get("keywords"), d.get("description")]):
                        continue
                    child_rows.append({
                        "task_id": task_id,
                        "title": (d.get("title") or "").strip() or None,
                        "url": (d.get("url") or "").strip() or None,
                        "keywords": (d.get("keywords") or "").strip() or None,
                        "description": (d.get("description") or "").strip() or None
                    })
                if child_rows:
                    supabase.table("task_details").insert(child_rows).execute()

def get_user_tasks(user):
    return supabase.table("tasks").select("*").eq("assigned_to", user).order("date").execute().data

def get_all_tasks():
    return supabase.table("tasks").select("*").order("date").execute().data

def update_task(task_id, task=None, assigned_to=None, status=None, remarks=None, quantity=None,
                date_val=None, deadline=None, title=None, url=None, keywords=None, description=None):
    """
    Kept for backward compatibility (single meta on parent). Child details live in task_details.
    """
    update_data = {}
    if task: update_data["task"] = task
    if assigned_to: update_data["assigned_to"] = assigned_to
    if status: update_data["status"] = status
    if remarks is not None: update_data["remarks"] = remarks
    if quantity is not None: update_data["quantity"] = int(quantity)
    if date_val: update_data["date"] = _to_datestr(date_val)
    if deadline: update_data["deadline"] = _to_datestr(deadline)
    # Legacy per-task meta (optional)
    if title is not None: update_data["title"] = title
    if url is not None: update_data["url"] = url
    if keywords is not None: update_data["keywords"] = keywords
    if description is not None: update_data["description"] = description

    if update_data:
        supabase.table("tasks").update(update_data).eq("id", task_id).execute()

def delete_tasks(task_ids):
    for tid in task_ids:
        supabase.table("tasks").delete().eq("id", tid).execute()

# ---------------- TASK DETAILS HELPERS ----------------
def get_task_details(task_id):
    return supabase.table("task_details").select("*").eq("task_id", task_id).order("id").execute().data

def add_task_detail_row(task_id, title=None, url=None, keywords=None, description=None):
    payload = {
        "task_id": task_id,
        "title": title or None,
        "url": url or None,
        "keywords": keywords or None,
        "description": description or None
    }
    supabase.table("task_details").insert(payload).execute()

def delete_task_detail_rows(detail_ids):
    if not detail_ids:
        return
    for did in detail_ids:
        supabase.table("task_details").delete().eq("id", did).execute()

# ---------------- STATE ----------------
st.title("📋 Advanced CRM - Task Manager")

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.username = ""
    st.session_state.role = ""

# holds unsaved (draft) details in Add Task form
if "details_draft" not in st.session_state:
    st.session_state.details_draft = []  # list of dicts

# ---------------- AUTH UI ----------------
if not st.session_state.logged_in:
    menu = ["Login", "Register"]
    choice = st.sidebar.selectbox("Menu", menu)

    if choice == "Register":
        st.subheader("Create New Account")
        new_user = st.text_input("Username")
        new_pass = st.text_input("Password", type="password")
        role = st.selectbox("Role", ["Admin", "Team"])
        if st.button("Register"):
            if not new_user or not new_pass:
                st.error("Username and password are required.")
            else:
                add_user(new_user, new_pass, role)
                st.success("User registered successfully! Go to Login.")

    elif choice == "Login":
        st.subheader("Login")
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        if st.button("Login"):
            user = login_user(username, password)
            if user:
                st.session_state.logged_in = True
                st.session_state.username = user["username"]
                st.session_state.role = user["role"]
                _rerun()
            else:
                st.error("Invalid credentials")

# ---------------- MAIN (ROLE-BASED) ----------------
else:
    st.sidebar.success(f"Logged in as {st.session_state.username} ({st.session_state.role})")
    if st.sidebar.button("Logout"):
        st.session_state.logged_in = False
        st.session_state.username = ""
        st.session_state.role = ""
        _rerun()

    if st.session_state.role == "Admin":
        menu = ["User Management", "Task List Management", "Add New Task", "Task Management", "Reports"]
    else:
        menu = ["My Tasks"]

    choice = st.sidebar.selectbox("Menu", menu)

    # ---------- USER MANAGEMENT (Admin) ----------
    if choice == "User Management" and st.session_state.role == "Admin":
        st.subheader("Manage Users")
        users = get_all_users()
        user_list = [f"{u['username']} ({u['role']})" for u in users]

        col1, col2 = st.columns(2)
        with col1:
            selected_users = st.multiselect("Select users to delete", user_list)
            if st.button("Delete Selected Users"):
                delete_users([u.split(" ")[0] for u in selected_users])
                st.success("Selected users deleted!")
                _rerun()

        with col2:
            edit_user_select = st.selectbox("Select a user to edit", ["--"] + user_list)
            if edit_user_select != "--":
                new_username = st.text_input("New Username")
                new_role = st.selectbox("New Role", ["Admin", "Team"])
                if st.button("Update User"):
                    old_username = edit_user_select.split(" ")[0]
                    update_user(old_username, new_username or old_username, new_role)
                    st.success("User updated!")
                    _rerun()

    # ---------- TASK LIST MANAGEMENT (Admin) ----------
    elif choice == "Task List Management" and st.session_state.role == "Admin":
        st.subheader("Manage Task Types")
        task_types = get_all_task_types()
        st.write("Existing Task Types:")
        st.write(task_types)
        new_task_type = st.text_input("Add New Task Type")
        if st.button("Add Task Type"):
            if new_task_type:
                add_task_type(new_task_type)
                st.success(f"Task type '{new_task_type}' added!")
                _rerun()

    # ---------- ADD NEW TASK (Admin) ----------
    elif choice == "Add New Task" and st.session_state.role == "Admin":
        st.subheader("Assign Tasks to Users")

        users = get_all_users()
        team_users = [u['username'] for u in users if u['role']=="Team"]
        selected_users = st.multiselect("Select Team Members", team_users)

        task_types = get_all_task_types()
        selected_tasks = st.multiselect("Select Tasks", task_types)

        st.markdown("#### Quantities")
        tasks_with_qty = {}
        for task in selected_tasks:
            tasks_with_qty[task] = st.number_input(f"Quantity for '{task}'", min_value=1, value=1, key=f"qty_{task}")

        # ---- multi-entry details draft ----
        st.markdown("### Optional Task Details (visible to assignee) — add multiple rows")
        with st.form("detail_add_form"):
            colA, colB = st.columns([1, 1])
            with colA:
                d_title = st.text_input("Title", key="detail_title")
                d_url = st.text_input("URL", key="detail_url")
            with colB:
                d_keywords = st.text_input("Keywords (comma-separated)", key="detail_keywords")
                d_description = st.text_area("Description", key="detail_description")
            add_clicked = st.form_submit_button("Add Detail to List")
            if add_clicked:
                st.session_state.details_draft.append({
                    "title": d_title.strip(),
                    "url": d_url.strip(),
                    "keywords": d_keywords.strip(),
                    "description": d_description.strip()
                })
                st.success("Detail added to list.")

        # Show current draft details
        if st.session_state.details_draft:
            st.markdown("**Draft Details:**")
            for i, d in enumerate(st.session_state.details_draft):
                with st.expander(f"Detail #{i+1}: {d.get('title') or '(no title)'}"):
                    st.write(f"**URL:** {d.get('url','')}")
                    st.write(f"**Keywords:** {d.get('keywords','')}")
                    st.write(f"**Description:** {d.get('description','')}")
                    if st.button("Remove this detail", key=f"remove_detail_{i}"):
                        st.session_state.details_draft.pop(i)
                        _rerun()

        st.divider()
        remarks = st.text_input("Remarks", "")
        colD, colE = st.columns(2)
        with colD:
            date_val = st.date_input("Task Date", value=date.today())
        with colE:
            deadline = st.date_input("Deadline", value=date.today())

        col_btn1, col_btn2 = st.columns([1, 1])
        with col_btn1:
            if st.button("Add Task"):
                if selected_users and tasks_with_qty:
                    assign_task_with_details(
                        selected_users,
                        tasks_with_qty,
                        _to_datestr(date_val),
                        _to_datestr(deadline),
                        remarks,
                        details_list=st.session_state.details_draft
                    )
                    st.success("Tasks assigned to selected users!")
                    st.session_state.details_draft = []
                else:
                    st.warning("Select at least one user and one task.")

        with col_btn2:
            if st.button("Clear Details List"):
                st.session_state.details_draft = []
                st.info("Draft details cleared.")

    # ---------- TASK MANAGEMENT (Admin) ----------
    elif choice == "Task Management" and st.session_state.role == "Admin":
        st.subheader("View/Edit/Delete Assigned Tasks")
        tasks = get_all_tasks()
        if tasks:
            task_list = [
                f"{t['id']} | {t['task']} | {t['assigned_to']} | {t['status']} | {t.get('date','')} | {t.get('deadline','')} | Qty:{t.get('quantity',1)}"
                for t in tasks
            ]
            colL, colR = st.columns([1, 1])
            with colL:
                selected_tasks_to_delete = st.multiselect("Select tasks to delete", task_list, key="delete_tasks_list")
                if st.button("Delete Selected Tasks"):
                    delete_tasks([int(t.split("|")[0]) for t in selected_tasks_to_delete])
                    st.success("Selected tasks deleted!")
                    _rerun()

            with colR:
                edit_task_select = st.selectbox("Select task to edit", ["--"] + task_list, key="edit_task_select")
                if edit_task_select != "--":
                    task_id = int(edit_task_select.split("|")[0])
                    details_rows = get_task_details(task_id)

                    task_types = get_all_task_types()
                    users = get_all_users()
                    new_task_name = st.selectbox("Task Name", task_types, key="adm_edit_task_name")
                    new_assigned_to = st.selectbox("Assigned To", [u['username'] for u in users if u['role']=="Team"], key="adm_edit_assigned_to")
                    new_status = st.selectbox("Status", ["Pending", "Half", "Done"], key="adm_edit_status")
                    new_remarks = st.text_input("Remarks", key="adm_edit_remarks")
                    new_quantity = st.number_input("Quantity", min_value=1, value=1, key="adm_edit_qty")
                    new_date_val = st.date_input("Date", key="adm_edit_date")
                    new_deadline = st.date_input("Deadline", key="adm_edit_deadline")

                    if st.button("Update Task"):
                        update_task(
                            task_id,
                            task=new_task_name,
                            assigned_to=new_assigned_to,
                            status=new_status,
                            remarks=new_remarks,
                            quantity=new_quantity,
                            date_val=_to_datestr(new_date_val),
                            deadline=_to_datestr(new_deadline)
                        )
                        st.success("Task updated!")
                        _rerun()

                    st.markdown("### Task Details (rows attached to this task)")
                    if details_rows:
                        del_ids = []
                        for d in details_rows:
                            with st.expander(f"#{d['id']} • {d.get('title') or '(no title)'}"):
                                st.write(f"**URL:** {d.get('url','')}")
                                st.write(f"**Keywords:** {d.get('keywords','')}")
                                st.write(f"**Description:** {d.get('description','')}")
                                if st.checkbox(f"Mark for delete #{d['id']}", key=f"del_detail_{d['id']}"):
                                    del_ids.append(d['id'])
                        if st.button("Delete Selected Details"):
                            delete_task_detail_rows(del_ids)
                            st.success("Selected details deleted.")
                            _rerun()
                    else:
                        st.info("No details yet.")

                    st.markdown("#### Add a new detail row to this task")
                    nd_title = st.text_input("Title", key="adm_new_detail_title")
                    nd_url = st.text_input("URL", key="adm_new_detail_url")
                    nd_keywords = st.text_input("Keywords (comma-separated)", key="adm_new_detail_keywords")
                    nd_description = st.text_area("Description", key="adm_new_detail_description")
                    if st.button("Add Detail Row"):
                        add_task_detail_row(task_id, nd_title, nd_url, nd_keywords, nd_description)
                        st.success("Detail row added.")
                        _rerun()
        else:
            st.info("No tasks found.")

    # ---------- REPORTS (Admin) ----------
    elif choice == "Reports" and st.session_state.role == "Admin":
        st.subheader("Task Reports")
        tasks = get_all_tasks()
        if tasks:
            df = pd.DataFrame(tasks)
            for col in ["date", "deadline"]:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors="coerce")

            user_filter = st.selectbox("Filter by User", ["All"] + [u['username'] for u in get_all_users()])
            month_filter = st.date_input("Filter by Month", value=date.today())

            filtered_df = df.copy()
            if user_filter != "All":
                filtered_df = filtered_df[filtered_df['assigned_to'] == user_filter]
            if "date" in filtered_df.columns:
                filtered_df = filtered_df[filtered_df['date'].dt.month == month_filter.month]

            st.write(filtered_df)

            if not filtered_df.empty and "assigned_to" in filtered_df.columns and "quantity" in filtered_df.columns:
                fig = px.bar(
                    filtered_df,
                    x="assigned_to",
                    y="quantity",
                    color="status",
                    barmode="stack",
                    title="Tasks Status by User"
                )
                st.plotly_chart(fig)
            else:
                st.info("No data to graph for the selected filter.")
        else:
            st.info("No tasks found.")

    # ---------- MY TASKS (Team) ----------
    elif choice == "My Tasks" and st.session_state.role != "Admin":
        st.subheader("My Tasks")

        my_tasks = get_user_tasks(st.session_state.username)
        df = pd.DataFrame(my_tasks) if my_tasks else pd.DataFrame(columns=[
            "id","task","status","remarks","quantity","date","deadline",
            "title","url","keywords","description"  # legacy single-meta (if present)
        ])

        if df.empty:
            st.info("No tasks assigned yet.")
        else:
            for col in ["date", "deadline"]:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors="coerce")

            view_mode = st.radio("View by", ["Date", "Month"], horizontal=True)
            if view_mode == "Date":
                picked_date = st.date_input("Select Date", value=date.today(), key="team_view_date")
                fdf = df[df["date"].dt.date == picked_date]
            else:
                picked_month = st.date_input("Select Month", value=date.today(), key="team_view_month")
                fdf = df[df["date"].dt.month == picked_month.month]

            if fdf.empty:
                st.info("No tasks for the selected period.")
            else:
                for _, row in fdf.sort_values(by=["date", "deadline", "id"]).iterrows():
                    header = f"#{row['id']} • {row.get('task','(no task)')} • {row.get('status','')}"
                    with st.expander(header):
                        st.markdown(f"**Task:** {row.get('task','')}")
                        st.markdown(f"**Quantity:** {row.get('quantity',1)}")
                        st.markdown(f"**Date:** {row['date'].date() if pd.notna(row['date']) else ''}")
                        st.markdown(f"**Deadline:** {row['deadline'].date() if pd.notna(row['deadline']) else ''}")
                        st.markdown("---")

                        # legacy single-meta (on parent)
                        legacy_has_any = any([
                            bool(row.get("title")),
                            bool(row.get("url")),
                            bool(row.get("keywords")),
                            bool(row.get("description"))
                        ])
                        if legacy_has_any:
                            legacy_rows = [{
                                "Title": row.get("title") or "",
                                "URL": _link(row.get("url") or ""),
                                "Keywords": row.get("keywords") or "",
                                "Description": row.get("description") or ""
                            }]
                            st.markdown("**Task Info (legacy fields):**")
                            st.dataframe(pd.DataFrame(legacy_rows), use_container_width=True)
                            st.markdown("---")

                        # multi-entry details
                        details_rows = get_task_details(row["id"])
                        if details_rows:
                            table = []
                            for d in details_rows:
                                table.append({
                                    "Title": d.get("title") or "",
                                    "URL": _link(d.get("url") or ""),
                                    "Keywords": d.get("keywords") or "",
                                    "Description": d.get("description") or ""
                                })
                            st.markdown("**Assigned Details:**")
                            st.dataframe(pd.DataFrame(table), use_container_width=True)
                        else:
                            st.info("No details attached to this task.")

                        st.markdown("---")
                        # Status & remarks update (team)
                        new_status = st.selectbox(
                            "Update Status",
                            ["Pending", "Done"],
                            index=0 if row.get("status") != "Done" else 1,
                            key=f"status_{row['id']}"
                        )
                        new_remarks = st.text_area(
                            "Remarks",
                            value=row.get("remarks") or "",
                            key=f"remarks_{row['id']}"
                        )
                        if st.button("Save Update", key=f"save_{row['id']}"):
                            update_task(
                                row["id"],
                                status=new_status,
                                remarks=new_remarks
                            )
                            st.success("Updated.")
                            _rerun()
