# ============================================================
# Advanced CRM - Task Manager (Projects + Monthly Targets + Cleanup)
# ============================================================
# ✅ RUN THIS SQL IN SUPABASE FIRST (SQL Editor)
#
# -- PROJECTS TABLE
# create table if not exists public.projects (
#   id bigint generated by default as identity primary key,
#   project_name text unique not null,
#   created_at timestamptz default now()
# );
# alter table public.projects enable row level security;
# do $$
# begin
#   if not exists (select 1 from pg_policies where policyname='projects_all') then
#     create policy projects_all on public.projects for all using (true) with check (true);
#   end if;
# end$$;
#
# -- ADD project COLUMN TO tasks
# alter table public.tasks add column if not exists project text;
# create index if not exists idx_tasks_project_date on public.tasks(project, date);
#
# -- MONTHLY TARGETS TABLE
# create table if not exists public.monthly_targets (
#   id bigint generated by default as identity primary key,
#   project text not null,
#   month date not null,
#   task text not null,
#   target_qty integer not null default 0,
#   created_at timestamptz default now(),
#   updated_at timestamptz default now()
# );
# do $$
# begin
#   if not exists (
#     select 1 from pg_constraint
#     where conrelid='public.monthly_targets'::regclass
#       and conname='monthly_targets_unique_project_month_task'
#   ) then
#     alter table public.monthly_targets
#       add constraint monthly_targets_unique_project_month_task unique(project, month, task);
#   end if;
# end$$;
# do $$
# begin
#   if not exists (
#     select 1 from pg_constraint
#     where conrelid='public.monthly_targets'::regclass
#       and conname='monthly_targets_target_nonneg'
#   ) then
#     alter table public.monthly_targets
#       add constraint monthly_targets_target_nonneg check (target_qty >= 0);
#   end if;
# end$$;
# create index if not exists idx_monthly_targets_lookup
#   on public.monthly_targets(project, month, task);
# alter table public.monthly_targets enable row level security;
# do $$
# begin
#   if not exists (select 1 from pg_policies where policyname='monthly_targets_all') then
#     create policy monthly_targets_all on public.monthly_targets for all using (true) with check (true);
#   end if;
# end$$;
#
# -- UPDATED_AT TRIGGER FOR monthly_targets (reuses your existing set_updated_at())
# do $$
# begin
#   if not exists (select 1 from pg_trigger where tgname='trg_monthly_targets_updated_at') then
#     create trigger trg_monthly_targets_updated_at
#       before update on public.monthly_targets
#       for each row execute function public.set_updated_at();
#   end if;
# end$$;
#
# ============================================================


# ---------------- IMPORTS ----------------
import streamlit as st
from supabase import create_client
from datetime import date, timedelta
import pandas as pd
import plotly.express as px
import json
import csv
import io
import re


# ---------------- PAGE & CLIENT ----------------
st.set_page_config(page_title="Advanced CRM - Task Manager", page_icon="📋", layout="wide")

SUPABASE_URL = "https://fijvjhbhxdbinqdiiytq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpanZqaGJoeGRiaW5xZGlpeXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTU5OTksImV4cCI6MjA3MzQ5MTk5OX0.aR5Sl9Z9wnCMQhRwHJ6dEXwAWTnxn-yxDqomL9KEHag"  # ⚠️ Don’t hardcode in production. Use Streamlit secrets.
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

try:
    _rerun = st.rerun
except AttributeError:
    _rerun = st.experimental_rerun


# ---------------- DEFAULT TASK TYPES ----------------
DEFAULT_TASK_TYPES = [
    "Forum Submission", "SBM", "Social Bookmarking", "Web 2.0/Profile Creation",
    "Podcast", "Classified Ads", "Forum Posting", "Q&A / Quora Submission",
    "Blog Submission", "Mini blog/article submission", "Tier-2 Backlinks",
    "Image Submission", "Blog SEO", "Document Sharing/PDF Sharing",
    "Infographic Submission / Business listings", "Guest Posting",
    "Competitor Backlinks", "Indexed Blogs (Wordpress, Blogger, Weebly)",
    "Social Signals", "On-page Blog", "Create Lost Backlinks"
]


# ---------------- UTIL ----------------
def _to_datestr(d):
    return d if isinstance(d, str) else d.strftime("%Y-%m-%d")

def _date_to_ymd(d: date) -> str:
    return d.strftime("%Y-%m-%d")

def _link(url: str) -> str:
    if not url:
        return ""
    return f"[{url}]({url})"

def _status_from_progress(done: int, total: int, fallback: str = "Pending") -> str:
    if total <= 0:
        return fallback
    if done <= 0:
        return "Pending"
    if done >= total:
        return "Done"
    return "Half"

def _now_utc():
    from datetime import datetime, timezone
    return datetime.now(timezone.utc)

def chunk_list(items, size=500):
    for i in range(0, len(items), size):
        yield items[i:i + size]

def month_start(d: date) -> date:
    return date(d.year, d.month, 1)

def month_range(year: int, month: int):
    start_dt = date(year, month, 1)
    if month == 12:
        end_dt = date(year + 1, 1, 1)
    else:
        end_dt = date(year, month + 1, 1)
    return start_dt, end_dt

def year_range(year: int):
    return date(year, 1, 1), date(year + 1, 1, 1)


# ---------------- TARGET LABEL -> MULTI TASK MATCHING (NEW) ----------------
def norm_text(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip()).lower()

def split_target_task_label(label: str) -> list[str]:
    """
    Splits a combined target label (your monthly target row) into parts.

    Example:
      'Web 2.0/Profile Creation/ /podcast/CLASSIFIED ADS/Forum Posting'
      -> ['Web 2.0', 'Profile Creation', 'podcast', 'CLASSIFIED ADS', 'Forum Posting']
    """
    if not label:
        return []
    parts = [p.strip() for p in str(label).split("/") if p and p.strip()]
    return parts

# Map fragments / variants to the real task names stored in tasks.task
TASK_ALIASES = {
    "web 2.0": "Web 2.0/Profile Creation",
    "profile creation": "Web 2.0/Profile Creation",

    "podcast": "Podcast",
    "classified ads": "Classified Ads",
    "classfied ads": "Classified Ads",  # common typo
    "forum posting": "Forum Posting",

    "document sharing": "Document Sharing/PDF Sharing",
    "pdf sharing": "Document Sharing/PDF Sharing",
    "document sharing/pdf sharing": "Document Sharing/PDF Sharing",

    "indexed blogs wordpress": "Indexed Blogs (Wordpress, Blogger, Weebly)",
    "indexed blogs": "Indexed Blogs (Wordpress, Blogger, Weebly)",

    "blog submission": "Blog Submission",
    "mini blog/article submission": "Mini blog/article submission",

    "social bookmarking": "Social Bookmarking",
    "social signals": "Social Signals",

    "competitor backlinks": "Competitor Backlinks",
    "tier-2 backlinks": "Tier-2 Backlinks",
    "q&a": "Q&A / Quora Submission",
    "quora submission": "Q&A / Quora Submission",
}


# ---------------- BULK PASTE PARSER (DETAILS) ----------------
def parse_bulk_details(text: str):
    """
    Supports:
      1) TSV paste: Title<TAB>URL<TAB>Keywords<TAB>Description
      2) CSV
      3) Pipe format: Title | URL | Keywords | Description
      4) Labeled blocks:
         Title: ...
         URL: ...
         Keywords: ...
         Description: ...
         (blank line separates entries)
    """
    if not text or not text.strip():
        return [], []

    raw = text.strip()

    label_re = re.compile(r"^(title|url|keywords|description)\s*:\s*(.*)$", re.I)
    lines = raw.splitlines()
    if any(label_re.match((l or "").strip() or "") for l in lines):
        rows = []
        cur = {"title": "", "url": "", "keywords": "", "description": ""}
        errors = []

        def flush():
            nonlocal cur
            if any(v.strip() for v in cur.values()):
                rows.append({
                    "title": cur["title"].strip(),
                    "url": cur["url"].strip(),
                    "keywords": cur["keywords"].strip(),
                    "description": cur["description"].strip()
                })
            cur = {"title": "", "url": "", "keywords": "", "description": ""}

        for ln in lines:
            s = (ln or "").strip()
            if not s:
                flush()
                continue

            m = label_re.match(s)
            if not m:
                cur["description"] = (cur["description"] + "\n" + s).strip()
                continue

            k = m.group(1).lower()
            v = m.group(2)
            cur[k] = (cur[k] + ("\n" if cur[k].strip() else "") + v).strip()

        flush()
        rows = [r for r in rows if any((r.get(k) or "").strip() for k in ("title", "url", "keywords", "description"))]
        return rows, errors

    sample_line = next((l for l in raw.splitlines() if l.strip()), "")
    delimiter = "\t" if "\t" in raw else None

    if delimiter is None:
        for d in ["|", ",", ";"]:
            if d in sample_line:
                delimiter = d
                break

    if delimiter is None:
        rows = [{"title": l.strip(), "url": "", "keywords": "", "description": ""} for l in raw.splitlines() if l.strip()]
        return rows, []

    f = io.StringIO(raw)
    reader = csv.reader(f, delimiter=delimiter)
    all_rows = [[(c or "").strip() for c in r] for r in reader if any(((c or "").strip() for c in r))]

    if not all_rows:
        return [], []

    header = [c.lower() for c in all_rows[0]]
    header_set = set(header)
    header_like = any(h in header_set for h in ["title", "url", "keywords", "description", "keyword", "link", "desc"])

    col_map = {"title": None, "url": None, "keywords": None, "description": None}

    if header_like:
        def idx(*names):
            for n in names:
                if n in header:
                    return header.index(n)
            return None

        col_map["title"] = idx("title")
        col_map["url"] = idx("url", "link")
        col_map["keywords"] = idx("keywords", "keyword")
        col_map["description"] = idx("description", "desc")
        data_rows = all_rows[1:]
    else:
        col_map["title"] = 0
        col_map["url"] = 1
        col_map["keywords"] = 2
        col_map["description"] = 3
        data_rows = all_rows

    rows = []
    errors = []

    for r in data_rows:
        def getv(key):
            j = col_map.get(key)
            if j is None:
                return ""
            return r[j].strip() if j < len(r) else ""

        row = {
            "title": getv("title"),
            "url": getv("url"),
            "keywords": getv("keywords"),
            "description": getv("description"),
        }
        if not any(v.strip() for v in row.values()):
            continue
        rows.append(row)

    return rows, errors


# ---------------- BULK PASTE PARSER (TARGETS) ----------------
def parse_bulk_targets(text: str):
    """
    Paste like:
    Task<TAB>Qty
    Task | Qty
    Task,Qty
    """
    rows = []
    if not text or not text.strip():
        return rows

    raw_lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    for ln in raw_lines:
        low = ln.lower()
        if low.startswith("task"):
            continue

        if "\t" in ln:
            a, b = ln.split("\t", 1)
        elif "|" in ln:
            a, b = ln.split("|", 1)
        elif "," in ln:
            a, b = ln.split(",", 1)
        else:
            parts = ln.split()
            if len(parts) < 2:
                continue
            a = " ".join(parts[:-1])
            b = parts[-1]

        task = (a or "").strip()
        qty_raw = (b or "").strip()
        if not task:
            continue

        try:
            qty = int(float(qty_raw)) if qty_raw else 0
        except Exception:
            qty = 0

        rows.append((task, qty))
    return rows


# ---------------- BULK CALLBACKS ----------------
def _clear_text_key(text_key: str):
    st.session_state[text_key] = ""

def _bulk_preview_to_state(text_key: str, out_key_prefix: str):
    text = st.session_state.get(text_key, "") or ""
    parsed, errs = parse_bulk_details(text)
    st.session_state[f"{out_key_prefix}_preview"] = parsed
    st.session_state[f"{out_key_prefix}_errs"] = errs

def _bulk_add_to_draft(text_key: str, out_key_prefix: str):
    text = st.session_state.get(text_key, "") or ""
    parsed, errs = parse_bulk_details(text)
    st.session_state[f"{out_key_prefix}_errs"] = errs
    st.session_state[f"{out_key_prefix}_added"] = len(parsed)

    if parsed:
        st.session_state.details_draft.extend(parsed)
        st.session_state[text_key] = ""

def _bulk_insert_into_task(task_id: int, text_key: str, out_key_prefix: str):
    text = st.session_state.get(text_key, "") or ""
    parsed, errs = parse_bulk_details(text)

    st.session_state[f"{out_key_prefix}_errs"] = errs
    st.session_state[f"{out_key_prefix}_added"] = 0

    if not parsed:
        return

    child_rows = []
    for d in parsed:
        if not any([d.get("title"), d.get("url"), d.get("keywords"), d.get("description")]):
            continue
        child_rows.append({
            "task_id": task_id,
            "title": (d.get("title") or "").strip() or None,
            "url": (d.get("url") or "").strip() or None,
            "keywords": (d.get("keywords") or "").strip() or None,
            "description": (d.get("description") or "").strip() or None
        })

    if child_rows:
        for chunk in chunk_list(child_rows, 500):
            supabase.table("task_details").insert(chunk).execute()

    st.session_state[f"{out_key_prefix}_added"] = len(child_rows)
    st.session_state[text_key] = ""


# ---------------- AUTH HELPERS ----------------
def add_user(username, password, role):
    supabase.table("users").insert({"username": username, "password": password, "role": role}).execute()

def update_user(old_username, new_username, new_role):
    supabase.table("users").update({"username": new_username, "role": new_role}).eq("username", old_username).execute()

def delete_users(usernames):
    for username in usernames:
        supabase.table("users").delete().eq("username", username).execute()

def login_user(username, password):
    response = supabase.table("users").select("*").eq("username", username).eq("password", password).execute()
    return response.data[0] if response.data else None

def get_all_users():
    return supabase.table("users").select("*").execute().data


# ---------------- PROJECT HELPERS ----------------
def get_all_projects():
    res = supabase.table("projects").select("*").order("project_name").execute()
    return [r["project_name"] for r in (res.data or [])]

def add_project(project_name: str):
    name = (project_name or "").strip()
    if not name:
        return
    supabase.table("projects").insert({"project_name": name}).execute()

def delete_projects(project_names, safe=True):
    if not project_names:
        return []
    skipped = []
    for name in project_names:
        name = (name or "").strip()
        if not name:
            continue

        if safe:
            used = supabase.table("tasks").select("id").eq("project", name).limit(1).execute()
            if getattr(used, "data", None) and len(used.data) > 0:
                skipped.append(name)
                continue

        supabase.table("projects").delete().eq("project_name", name).execute()
    return skipped


# ---------------- TASK TYPE HELPERS ----------------
def get_all_task_types():
    response = supabase.table("task_types").select("*").execute()
    if not response.data:
        for t in DEFAULT_TASK_TYPES:
            supabase.table("task_types").insert({"task_name": t}).execute()
        response = supabase.table("task_types").select("*").execute()
    return [t["task_name"] for t in response.data]

def add_task_type(task_name):
    supabase.table("task_types").insert({"task_name": task_name}).execute()

def delete_task_types(task_names, safe=True):
    if not task_names:
        return []
    skipped = []
    for name in task_names:
        if safe:
            used = supabase.table("tasks").select("id").eq("task", name).limit(1).execute()
            if getattr(used, "data", None) and len(used.data) > 0:
                skipped.append(name)
                continue
        supabase.table("task_types").delete().eq("task_name", name).execute()
    return skipped


# ---------------- MONTHLY TARGET HELPERS ----------------
def upsert_monthly_target(project: str, month_dt: date, task: str, target_qty: int):
    payload = {
        "project": (project or "").strip(),
        "month": _to_datestr(month_start(month_dt)),
        "task": (task or "").strip(),
        "target_qty": int(target_qty),
        "updated_at": _now_utc().isoformat()
    }
    supabase.table("monthly_targets").upsert(payload, on_conflict="project,month,task").execute()

def get_monthly_targets(project: str, month_dt: date):
    m = _to_datestr(month_start(month_dt))
    return (
        supabase.table("monthly_targets")
        .select("*")
        .eq("project", project)
        .eq("month", m)
        .order("task")
        .execute()
        .data
    )


# ---------------- TASK HELPERS ----------------
def assign_task_with_details(project, users, tasks_with_qty, date_val, deadline, remarks="", details_list=None):
    date_str = _to_datestr(date_val)
    deadline_str = _to_datestr(deadline)
    details_list = details_list or []
    project = (project or "").strip() or None

    for user in users:
        for task_name, qty in tasks_with_qty.items():
            payload = {
                "project": project,
                "assigned_to": user,
                "task": task_name,
                "status": "Pending",
                "date": date_str,
                "deadline": deadline_str,
                "quantity": int(qty),
                "quantity_done": 0,
                "remarks": remarks,
                "updated_at": _now_utc().isoformat()
            }

            ins = supabase.table("tasks").insert(payload).execute()

            task_id = None
            if getattr(ins, "data", None):
                try:
                    task_id = ins.data[0]["id"]
                except (IndexError, KeyError, TypeError):
                    task_id = None

            if task_id is None:
                lookup = (
                    supabase.table("tasks")
                    .select("id")
                    .eq("assigned_to", user)
                    .eq("task", task_name)
                    .eq("date", date_str)
                    .eq("deadline", deadline_str)
                    .order("id", desc=True)
                    .limit(1)
                    .execute()
                )
                if getattr(lookup, "data", None):
                    task_id = lookup.data[0]["id"]

            if not task_id:
                continue

            if details_list:
                child_rows = []
                for d in details_list:
                    if not any([d.get("title"), d.get("url"), d.get("keywords"), d.get("description")]):
                        continue
                    child_rows.append({
                        "task_id": task_id,
                        "title": (d.get("title") or "").strip() or None,
                        "url": (d.get("url") or "").strip() or None,
                        "keywords": (d.get("keywords") or "").strip() or None,
                        "description": (d.get("description") or "").strip() or None
                    })
                if child_rows:
                    for chunk in chunk_list(child_rows, 500):
                        supabase.table("task_details").insert(chunk).execute()

def get_user_tasks(user):
    return supabase.table("tasks").select("*").eq("assigned_to", user).order("date").execute().data

def get_all_tasks():
    return supabase.table("tasks").select("*").order("date").execute().data

def update_task(task_id, task=None, assigned_to=None, status=None, remarks=None, quantity=None,
                date_val=None, deadline=None, project=None,
                title=None, url=None, keywords=None, description=None,
                quantity_done=None):
    update_data = {"updated_at": _now_utc().isoformat()}
    if project is not None:
        update_data["project"] = project
    if task:
        update_data["task"] = task
    if assigned_to:
        update_data["assigned_to"] = assigned_to
    if status:
        update_data["status"] = status
    if remarks is not None:
        update_data["remarks"] = remarks
    if quantity is not None:
        update_data["quantity"] = int(quantity)
    if date_val:
        update_data["date"] = _to_datestr(date_val)
    if deadline:
        update_data["deadline"] = _to_datestr(deadline)
    if title is not None:
        update_data["title"] = title
    if url is not None:
        update_data["url"] = url
    if keywords is not None:
        update_data["keywords"] = keywords
    if description is not None:
        update_data["description"] = description
    if quantity_done is not None:
        update_data["quantity_done"] = int(max(0, quantity_done))

    supabase.table("tasks").update(update_data).eq("id", task_id).execute()

def delete_tasks(task_ids):
    for tid in task_ids:
        supabase.table("tasks").delete().eq("id", tid).execute()


# ---------------- TASK DETAILS HELPERS ----------------
def get_task_details(task_id):
    return supabase.table("task_details").select("*").eq("task_id", task_id).order("id").execute().data

def add_task_detail_row(task_id, title=None, url=None, keywords=None, description=None):
    payload = {"task_id": task_id, "title": title or None, "url": url or None, "keywords": keywords or None, "description": description or None}
    supabase.table("task_details").insert(payload).execute()

def delete_task_detail_rows(detail_ids):
    if not detail_ids:
        return
    for did in detail_ids:
        supabase.table("task_details").delete().eq("id", did).execute()

def get_task_details_bulk(task_ids):
    if not task_ids:
        return []
    return (
        supabase.table("task_details")
        .select("*")
        .in_("task_id", task_ids)
        .order("task_id").order("id")
        .execute()
    ).data


# ---------------- TO-DO HELPERS ----------------
def add_todo(date_val, title, notes, created_by, status="Pending"):
    payload = {
        "date": _to_datestr(date_val),
        "title": title.strip(),
        "notes": (notes or "").strip(),
        "status": status,
        "created_by": created_by,
        "updated_at": _now_utc().isoformat()
    }
    supabase.table("todos").insert(payload).execute()

def get_todos(from_date=None, to_date=None, status=None, created_by=None):
    q = supabase.table("todos").select("*").order("date").order("id")
    if from_date:
        q = q.gte("date", _to_datestr(from_date))
    if to_date:
        q = q.lte("date", _to_datestr(to_date))
    if status and status in ("Pending", "Done"):
        q = q.eq("status", status)
    if created_by:
        q = q.eq("created_by", created_by)
    return q.execute().data

def update_todo(todo_id, title=None, notes=None, status=None, date_val=None):
    data = {"updated_at": _now_utc().isoformat()}
    if title is not None:
        data["title"] = title.strip()
    if notes is not None:
        data["notes"] = (notes or "").strip()
    if status in ("Pending", "Done"):
        data["status"] = status
    if date_val is not None:
        data["date"] = _to_datestr(date_val)
    supabase.table("todos").update(data).eq("id", todo_id).execute()

def delete_todos(todo_ids):
    for tid in todo_ids:
        supabase.table("todos").delete().eq("id", tid).execute()


# ---------------- CLEANUP HELPERS ----------------
def delete_tasks_by_range(start_dt: date, end_dt_exclusive: date, project: str = None):
    q = (
        supabase.table("tasks")
        .delete()
        .gte("date", _date_to_ymd(start_dt))
        .lt("date", _date_to_ymd(end_dt_exclusive))
    )
    if project and project != "All":
        q = q.eq("project", project)
    q.execute()

def delete_todos_by_range(start_dt: date, end_dt_exclusive: date, created_by: str = None):
    q = (
        supabase.table("todos")
        .delete()
        .gte("date", _date_to_ymd(start_dt))
        .lt("date", _date_to_ymd(end_dt_exclusive))
    )
    if created_by:
        q = q.eq("created_by", created_by)
    q.execute()

def delete_targets_by_range(start_month_dt: date, end_month_exclusive_dt: date, project: str = None):
    q = (
        supabase.table("monthly_targets")
        .delete()
        .gte("month", _date_to_ymd(month_start(start_month_dt)))
        .lt("month", _date_to_ymd(month_start(end_month_exclusive_dt)))
    )
    if project and project != "All":
        q = q.eq("project", project)
    q.execute()


# ---------------- DESKTOP NOTIFICATIONS ----------------
def show_browser_notifications(messages):
    if not messages:
        return
    payload = {"messages": messages}
    html = f"""
    <script>
      const data = {json.dumps(payload)};
      (async () => {{
        if (!("Notification" in window)) return;
        let perm = Notification.permission;
        try {{
          if (perm !== "granted") perm = await Notification.requestPermission();
        }} catch (e) {{}}
        if (perm === "granted") {{
          data.messages.forEach((m, i) => {{
            setTimeout(() => new Notification(m.title, {{ body: m.body }}), i * 400);
          }});
        }}
      }})();
    </script>
    """
    st.components.v1.html(html, height=0)

def poll_for_new_done_events(init=False):
    if "done_seen_ids" not in st.session_state:
        st.session_state.done_seen_ids = set()

    since = (_now_utc() - timedelta(hours=24)).isoformat()
    try:
        q = supabase.table("tasks").select("*").eq("status", "Done").order("updated_at", desc=True)
        tasks = q.gte("updated_at", since).limit(500).execute().data
    except Exception:
        tasks = supabase.table("tasks").select("*").eq("status", "Done").order("id", desc=True).limit(500).execute().data

    new_msgs = []
    current_done_ids = set()
    for t in tasks or []:
        tid = int(t["id"])
        current_done_ids.add(tid)
        if init:
            continue
        if tid not in st.session_state.done_seen_ids:
            who = t.get("assigned_to", "User")
            task_name = t.get("task", "Task")
            new_msgs.append({"title": "Task Completed", "body": f"{who} marked '{task_name}' as Done (#{tid})."})

    st.session_state.done_seen_ids |= current_done_ids
    if new_msgs:
        show_browser_notifications(new_msgs)


# ---------------- STATE ----------------
st.title("📋 Advanced CRM - Task Manager")

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.username = ""
    st.session_state.role = ""

if "details_draft" not in st.session_state:
    st.session_state.details_draft = []


# ---------------- AUTH UI ----------------
if not st.session_state.logged_in:
    menu = ["Login", "Register"]
    choice = st.sidebar.selectbox("Menu", menu)

    if choice == "Register":
        st.subheader("Create New Account")
        new_user = st.text_input("Username")
        new_pass = st.text_input("Password", type="password")
        role = st.selectbox("Role", ["Admin", "Team"])
        if st.button("Register"):
            if not new_user or not new_pass:
                st.error("Username and password are required.")
            else:
                add_user(new_user, new_pass, role)
                st.success("User registered successfully! Go to Login.")

    elif choice == "Login":
        st.subheader("Login")
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        if st.button("Login"):
            user = login_user(username, password)
            if user:
                st.session_state.logged_in = True
                st.session_state.username = user["username"]
                st.session_state.role = user["role"]
                _rerun()
            else:
                st.error("Invalid credentials")


# ---------------- MAIN (ROLE-BASED) ----------------
else:
    st.sidebar.success(f"Logged in as {st.session_state.username} ({st.session_state.role})")
    if st.sidebar.button("Logout"):
        st.session_state.logged_in = False
        st.session_state.username = ""
        st.session_state.role = ""
        _rerun()

    if st.session_state.role == "Admin":
        menu = [
            "User Management",
            "Task List Management",
            "Add New Task",
            "Task Management",
            "To-Do",
            "Reports",
            "Monthly Targets",
            "Data Cleanup",
        ]
    else:
        menu = ["My Tasks", "My To-Do"]

    choice = st.sidebar.selectbox("Menu", menu)

    if st.session_state.role == "Admin":
        poll_for_new_done_events(init=True)

    # ---------- USER MANAGEMENT (Admin) ----------
    if choice == "User Management" and st.session_state.role == "Admin":
        st.subheader("Manage Users")
        users = get_all_users()
        user_list = [f"{u['username']} ({u['role']})" for u in users]

        col1, col2 = st.columns(2)
        with col1:
            selected_users = st.multiselect("Select users to delete", user_list)
            if st.button("Delete Selected Users"):
                delete_users([u.split(" ")[0] for u in selected_users])
                st.success("Selected users deleted!")
                _rerun()

        with col2:
            edit_user_select = st.selectbox("Select a user to edit", ["--"] + user_list)
            if edit_user_select != "--":
                new_username = st.text_input("New Username")
                new_role = st.selectbox("New Role", ["Admin", "Team"])
                if st.button("Update User"):
                    old_username = edit_user_select.split(" ")[0]
                    update_user(old_username, new_username or old_username, new_role)
                    st.success("User updated!")
                    _rerun()

    # ---------- TASK LIST MANAGEMENT (Admin) ----------
    elif choice == "Task List Management" and st.session_state.role == "Admin":
        st.subheader("Manage Task Types + Projects")
        tab1, tab2 = st.tabs(["Task Types", "Projects"])

        with tab1:
            task_types = get_all_task_types()
            col_a, col_b = st.columns([1, 1])
            with col_a:
                st.markdown("**Existing Task Types**")
                st.write(task_types)

                new_task_type = st.text_input("Add New Task Type", key="add_task_type_txt")
                if st.button("Add Task Type", key="add_task_type_btn"):
                    if new_task_type:
                        add_task_type(new_task_type.strip())
                        st.success(f"Added: {new_task_type}")
                        _rerun()
                    else:
                        st.warning("Enter a task type name.")

            with col_b:
                st.markdown("**Delete Task Types**")
                types_to_delete = st.multiselect("Select task types to delete", task_types, key="del_task_types_ms")
                safe_delete = st.checkbox("Prevent deletion if any task uses the type (recommended)", value=True, key="safe_del_task_types")

                if st.button("Delete Selected Types", key="del_task_types_btn"):
                    if not types_to_delete:
                        st.info("Select at least one type.")
                    else:
                        skipped = delete_task_types(types_to_delete, safe=safe_delete)
                        deleted = list(set(types_to_delete) - set(skipped))
                        if deleted:
                            st.success("Deleted: " + ", ".join(sorted(deleted)))
                        if skipped:
                            st.warning("Skipped (in use): " + ", ".join(sorted(skipped)))
                        _rerun()

        with tab2:
            try:
                projects = get_all_projects()
            except Exception:
                st.error("Projects table not found. Run the SQL at the top of this file in Supabase.")
                st.stop()

            col_a, col_b = st.columns([1, 1])
            with col_a:
                st.markdown("**Existing Projects**")
                st.write(projects)

                new_project = st.text_input("Add New Project", key="add_project_txt")
                if st.button("Add Project", key="add_project_btn"):
                    if new_project.strip():
                        add_project(new_project.strip())
                        st.success(f"Added: {new_project}")
                        _rerun()
                    else:
                        st.warning("Enter a project name.")

            with col_b:
                st.markdown("**Delete Projects**")
                proj_to_delete = st.multiselect("Select projects to delete", projects, key="del_projects_ms")
                safe_delete_p = st.checkbox("Prevent deletion if any task uses the project (recommended)", value=True, key="safe_del_projects")
                if st.button("Delete Selected Projects", key="del_projects_btn"):
                    if not proj_to_delete:
                        st.info("Select at least one project.")
                    else:
                        skipped = delete_projects(proj_to_delete, safe=safe_delete_p)
                        deleted = list(set(proj_to_delete) - set(skipped))
                        if deleted:
                            st.success("Deleted: " + ", ".join(sorted(deleted)))
                        if skipped:
                            st.warning("Skipped (in use): " + ", ".join(sorted(skipped)))
                        _rerun()

    # ---------- MONTHLY TARGETS (Admin) ----------
    elif choice == "Monthly Targets" and st.session_state.role == "Admin":
        st.subheader("Monthly Targets (Project-wise)")

        try:
            projects = get_all_projects()
        except Exception:
            st.error("Projects table not found. Run the SQL at the top of this file in Supabase.")
            st.stop()

        if not projects:
            st.info("Add at least 1 project in Task List Management → Projects.")
            st.stop()

        c1, c2 = st.columns([2, 1])
        with c1:
            project = st.selectbox("Project", projects, key="mt_project")
        with c2:
            picked_month = st.date_input("Month", value=date.today(), key="mt_month")

        task_types = get_all_task_types()

        st.markdown("### Add / Update Target (single)")
        a1, a2, a3 = st.columns([2, 1, 1])
        with a1:
            t_task = st.selectbox("Task", task_types, key="mt_task")
        with a2:
            t_qty = st.number_input("Target Qty", min_value=0, value=0, step=1, key="mt_qty")
        with a3:
            if st.button("Save Target", key="mt_save"):
                upsert_monthly_target(project, picked_month, t_task, int(t_qty))
                st.success("Saved.")
                _rerun()

        st.divider()
        st.markdown("### Bulk paste targets")
        st.caption("Paste like: Task<TAB>Qty OR Task | Qty OR Task,Qty")
        bulk_text = st.text_area("Paste here", height=180, key="mt_bulk")

        colx1, colx2 = st.columns([1, 1])
        with colx1:
            if st.button("Preview Bulk", key="mt_preview"):
                parsed = parse_bulk_targets(bulk_text)
                if not parsed:
                    st.info("No valid rows found.")
                else:
                    st.dataframe(pd.DataFrame(parsed, columns=["Task", "Target Qty"]), use_container_width=True)

        with colx2:
            if st.button("Import Bulk Targets", key="mt_import"):
                parsed = parse_bulk_targets(bulk_text)
                if not parsed:
                    st.warning("No valid rows found.")
                else:
                    for task_name, qty in parsed:
                        upsert_monthly_target(project, picked_month, task_name, int(qty))
                    st.success(f"Imported {len(parsed)} targets.")
                    _rerun()

        st.divider()
        st.markdown("### Current Targets")
        existing = get_monthly_targets(project, picked_month)
        if not existing:
            st.info("No targets set for this month/project.")
        else:
            df_t = pd.DataFrame(existing)[["task", "target_qty"]].sort_values("task")
            st.dataframe(df_t, use_container_width=True)

    # ---------- REPORTS (Admin) ----------
    elif choice == "Reports" and st.session_state.role == "Admin":
        st.subheader("Task Reports (Project + Targets)")

        tasks = get_all_tasks()
        if not tasks:
            st.info("No tasks found.")
            st.stop()

        df = pd.DataFrame(tasks)
        for col in ["date", "deadline"]:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors="coerce")

        df["status"] = df.get("status", "Pending").fillna("Pending")
        df["quantity"] = df.get("quantity", 1).fillna(1).astype(int)
        df["quantity_done"] = df.get("quantity_done", 0).fillna(0).astype(int)
        df["remaining_units"] = (df["quantity"] - df["quantity_done"]).clip(lower=0).astype(int)

        users = get_all_users()
        user_filter = st.selectbox("Filter by User", ["All"] + [u["username"] for u in users])

        try:
            projects = get_all_projects()
            project_filter = st.selectbox("Filter by Project", ["All"] + projects)
        except Exception:
            project_filter = "All"
            st.info("Projects table not found. Project filter disabled.")

        col_f1, col_f2 = st.columns([1, 2])
        with col_f1:
            view_mode = st.radio("View", ["Date-wise", "Month-wise"], horizontal=True)

        filtered_df = df.copy()
        if user_filter != "All":
            filtered_df = filtered_df[filtered_df["assigned_to"] == user_filter]
        if project_filter != "All":
            filtered_df = filtered_df[filtered_df["project"].fillna("") == project_filter]

        picked_period = None
        with col_f2:
            if view_mode == "Date-wise":
                picked_date = st.date_input("Select Date", value=date.today(), key="admin_report_date")
                filtered_df = filtered_df[filtered_df["date"].dt.date == picked_date]
            else:
                valid = filtered_df[filtered_df["date"].notna()].copy()
                unique_months = sorted(valid["date"].dt.to_period("M").unique()) if not valid.empty else []
                if unique_months:
                    labels = [p.strftime("%B %Y") for p in unique_months]
                    picked_label = st.selectbox("Select Month", labels, index=len(labels) - 1)
                    picked_period = unique_months[labels.index(picked_label)]
                    filtered_df = filtered_df[filtered_df["date"].dt.to_period("M") == picked_period]
                else:
                    st.info("No month data available for selected filters.")
                    filtered_df = filtered_df.iloc[0:0]

        if filtered_df.empty:
            st.info("No data for the selected filters.")
            st.stop()

        c1, c2, c3, c4, c5, c6 = st.columns(6)
        c1.metric("Tasks", int(len(filtered_df)))
        c2.metric("Done", int((filtered_df["status"] == "Done").sum()))
        c3.metric("Half", int((filtered_df["status"] == "Half").sum()))
        c4.metric("Pending", int((filtered_df["status"] == "Pending").sum()))
        c5.metric("Units Done", int(filtered_df["quantity_done"].sum()))
        c6.metric("Units Pending", int(filtered_df["remaining_units"].sum()))

        st.divider()
        st.markdown("## Project Status Breakdown")

        by_user_task = (
            filtered_df.groupby(["assigned_to", "task"], as_index=False)[["quantity_done", "remaining_units", "quantity"]]
            .sum()
            .rename(columns={"quantity_done": "done_units", "remaining_units": "pending_units", "quantity": "assigned_units"})
        )
        st.markdown("### Task-wise units by user")
        st.dataframe(by_user_task.sort_values(["assigned_to", "task"]), use_container_width=True)

        by_task = (
            filtered_df.groupby("task", as_index=False)[["quantity_done", "remaining_units", "quantity"]]
            .sum()
            .rename(columns={"quantity_done": "done_units", "remaining_units": "pending_units", "quantity": "assigned_units"})
        )
        st.markdown("### Task-wise totals (overall)")
        st.dataframe(by_task.sort_values("pending_units", ascending=False), use_container_width=True)

        st.markdown("### Pending items (one by one)")
        pending_list = filtered_df[(filtered_df["remaining_units"] > 0) | (filtered_df["status"] != "Done")].copy()
        show_cols = ["id", "project", "task", "assigned_to", "status", "quantity", "quantity_done", "remaining_units", "date", "deadline", "remarks"]
        show_cols = [c for c in show_cols if c in pending_list.columns]
        st.dataframe(pending_list[show_cols].sort_values(["deadline", "date", "id"], na_position="last"), use_container_width=True)

        # ✅ Target vs achieved (Month-wise + specific project) — FIXED FOR MULTI-TASK TARGET LABELS
        if view_mode == "Month-wise" and picked_period is not None and project_filter != "All":
            st.divider()
            st.markdown("## Target vs Achieved (Selected Project + Month)")

            month_dt = date(int(picked_period.year), int(picked_period.month), 1)
            targets = get_monthly_targets(project_filter, month_dt)
            tgt_df = pd.DataFrame(targets) if targets else pd.DataFrame(columns=["task", "target_qty"])

            # Actual done units by task (normalize)
            actual_by_task = (
                filtered_df.groupby("task", as_index=False)[["quantity_done"]]
                .sum()
                .rename(columns={"quantity_done": "done_units"})
            )
            actual_by_task["task_norm"] = actual_by_task["task"].astype(str).apply(norm_text)

            # Lookup: normalized task -> done units
            done_lookup = dict(zip(actual_by_task["task_norm"], actual_by_task["done_units"]))

            rows_out = []
            for _, r in tgt_df.iterrows():
                target_label = str(r.get("task") or "").strip()
                target_qty = int(r.get("target_qty") or 0)

                parts = split_target_task_label(target_label)

                # Always treat a target label as a "bucket":
                # - if it contains '/', count all mapped parts
                # - if not, count exact task match
                if "/" in target_label and parts:
                    mapped_tasks = []
                    for p in parts:
                        key = norm_text(p)
                        mapped = TASK_ALIASES.get(key, p.strip())
                        mapped_tasks.append(mapped)

                    done_sum = 0
                    used_tasks = []
                    for tname in mapped_tasks:
                        dn = int(done_lookup.get(norm_text(tname), 0))
                        if dn > 0:
                            used_tasks.append(tname)
                        done_sum += dn

                    rows_out.append({
                        "task": target_label,
                        "target_qty": target_qty,
                        "done_units": int(done_sum),
                        "pending_to_target": max(0, target_qty - int(done_sum)),
                        "matched_tasks": ", ".join(used_tasks) if used_tasks else ""
                    })
                else:
                    dn = int(done_lookup.get(norm_text(target_label), 0))
                    rows_out.append({
                        "task": target_label,
                        "target_qty": target_qty,
                        "done_units": dn,
                        "pending_to_target": max(0, target_qty - dn),
                        "matched_tasks": target_label if dn else ""
                    })

            merged = pd.DataFrame(rows_out)

            t1, t2, t3 = st.columns(3)
            t1.metric("Target", int(merged["target_qty"].sum()))
            t2.metric("Done", int(merged["done_units"].sum()))
            t3.metric("Pending to Target", int(merged["pending_to_target"].sum()))

            # matched_tasks helps you verify what counted in each bucket
            st.dataframe(merged.sort_values("pending_to_target", ascending=False), use_container_width=True)

        st.divider()
        st.markdown("## Charts")

        agg_units = (
            filtered_df.groupby("assigned_to", as_index=False)[["quantity_done", "quantity"]]
            .sum()
            .rename(columns={"quantity_done": "completed_units", "quantity": "assigned_units"})
        )
        agg_units["remaining_units"] = (agg_units["assigned_units"] - agg_units["completed_units"]).clip(lower=0)
        agg_melt = agg_units.melt(
            id_vars="assigned_to",
            value_vars=["completed_units", "remaining_units"],
            var_name="Metric",
            value_name="Units"
        )
        fig = px.bar(agg_melt, x="assigned_to", y="Units", color="Metric", barmode="stack",
                     title="Completed vs Remaining Units by User")
        st.plotly_chart(fig, use_container_width=True)

        count_by_status = filtered_df.groupby("status", as_index=False)["id"].count().rename(columns={"id": "Tasks"})
        fig2 = px.bar(count_by_status, x="status", y="Tasks", title="Task Count by Status (Selected Period)")
        st.plotly_chart(fig2, use_container_width=True)

    else:
        st.info("Other sections omitted here to keep this answer readable. Paste this full file over your existing one.")
